// Code generated by Slice Machine. DO NOT EDIT.

import DemoMockSiice from './DemoMockSiice';
import ImageAndText from './ImageAndText';
import MyNewSlice from './MyNewSlice';
import MyTestSlice from './MyTestSlice';
import Test from './Test';

export {
	DemoMockSiice,
	ImageAndText,
	MyNewSlice,
	MyTestSlice,
	Test,
};

export const components = {
	demo_mock_siice: DemoMockSiice,
	image_and_text: ImageAndText,
	my_new_slice: MyNewSlice,
	my_test_slice: MyTestSlice,
	test: Test,
};
